/**
 * MQTT development setup (plan §13.2, M6.2). Runs OpenSSL and mosquitto_passwd in containers, so nothing is
 * needed on the host except Docker.
 *   npx tsx scripts/mqtt-setup.ts certs   dev CA + broker certificate (SAN: localhost, mosquitto, 127.0.0.1)
 *   npx tsx scripts/mqtt-setup.ts users   one username + random password per device, ACLs from the device registry
 * Outputs (git-ignored): infra/mosquitto/{certs/,passwd,acl} and .mqtt-creds.env (passwords for backend and simulator).
 */
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const root = fileURLToPath(new URL('..', import.meta.url));
const dir = fileURLToPath(new URL('../infra/mosquitto/', import.meta.url));
const docker = (...args: string[]) => execFileSync('docker', args, { stdio: ['ignore', 'pipe', 'inherit'] }).toString();

function certs() {
  mkdirSync(`${dir}certs`, { recursive: true });
  docker('run', '--rm', '-v', `${dir}certs:/certs`, '--entrypoint', 'sh', 'alpine/openssl:3.3.2', '-c', [
    'set -e', 'cd /certs',
    'openssl req -x509 -newkey rsa:3072 -nodes -days 825 -subj "/CN=FTMS dev CA" -keyout ca.key -out ca.crt',
    'openssl req -newkey rsa:3072 -nodes -subj "/CN=mosquitto" -keyout server.key -out server.csr',
    'printf "subjectAltName=DNS:localhost,DNS:mosquitto,IP:127.0.0.1\\nextendedKeyUsage=serverAuth\\n" > ext.cnf',
    'openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -days 825 -extfile ext.cnf -out server.crt',
    'rm server.csr ext.cnf ca.srl', 'chmod 644 *',
  ].join(' && '));
  console.log('wrote infra/mosquitto/certs/{ca.crt,ca.key,server.crt,server.key}');
}

function readEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  return Object.fromEntries(readFileSync(path, 'utf8').split(/\r?\n/).map((l) => /^([A-Z0-9_]+)=(.*)$/.exec(l)).filter((m) => m).map((m) => [m![1]!, m![2]!]));
}

/** Environment variable that holds a device's MQTT password, e.g. ctrl-A → MQTT_PASSWORD_CTRL_A. */
export const passwordVar = (user: string) => `MQTT_PASSWORD_${user.toUpperCase().replace(/[^A-Z0-9]/g, '_')}`;

async function users() {
  const env = { ...readEnvFile(`${root}.env`), ...process.env };
  const db = new pg.Client({ connectionString: env.DATABASE_OWNER_URL });
  await db.connect();
  const { rows } = await db.query("SELECT device_id, kind, junction_id, approach FROM devices WHERE status = 'ACTIVE' ORDER BY device_id");
  await db.end();
  const simulation = env.SIMULATION_MODE === 'true';

  const acl = ['# Generated by `npm run mqtt:users` from the device registry. Do not edit.', '', '# Backend', 'user ftms-backend', 'topic readwrite ftms/v1/#', ...(simulation ? ['topic write ftms/sim/#'] : []), ''];
  const creds: [string, string][] = [['ftms-backend', randomBytes(24).toString('base64url')]];
  for (const d of rows) {
    const j = d.junction_id;
    creds.push([d.device_id, randomBytes(24).toString('base64url')]);
    if (d.kind === 'CONTROLLER') {
      acl.push(`# Controller of junction ${j}`, `user ${d.device_id}`,
        `topic read  ftms/v1/junctions/${j}/controller/commands`,
        ...['acks', 'heartbeat', 'status'].map((t) => `topic write ftms/v1/junctions/${j}/controller/${t}`),
        `topic write ftms/v1/junctions/${j}/devices/status`, 'topic read  ftms/v1/backend/status',
        ...(simulation ? [`topic read  ftms/sim/junctions/${j}/control`] : []), '');
    } else {
      acl.push(`# Sensor on the ${d.approach} approach of junction ${j}`, `user ${d.device_id}`, `topic write ftms/v1/junctions/${j}/sensors/${d.approach}/events`, '');
    }
  }
  writeFileSync(`${dir}acl`, `${acl.join('\n')}\n`);

  // mosquitto_passwd hashes the passwords (PBKDF2-SHA512) inside the broker image.
  writeFileSync(`${dir}passwd`, creds.map(([u, p]) => `${u}:${p}`).join('\n') + '\n');
  docker('run', '--rm', '-v', `${dir}:/m`, '--entrypoint', 'sh', 'eclipse-mosquitto:2.0.20', '-c', 'mosquitto_passwd -U /m/passwd && chmod 644 /m/passwd');
  writeFileSync(`${root}.mqtt-creds.env`, `${creds.map(([u, p]) => `${passwordVar(u)}=${p}`).join('\n')}\n`);
  console.log(`wrote infra/mosquitto/{passwd,acl} for ${creds.length} users and .mqtt-creds.env (git-ignored)`);
  console.log('restart the broker to load them: docker compose --profile mqtt restart mosquitto');
}

const cmd = process.argv[2];
if (cmd === 'certs') certs();
else if (cmd === 'users') await users();
else { console.error('usage: mqtt-setup.ts certs|users'); process.exit(1); }
